targets:
  $default:
    builders:
      json_serializable_immutable_collections:
        # configure your options here, same as json_serializable
        options:
          any_map: true
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      json_serializable:json_serializable:
        generate_for:
          # exclude everything to avoid conflicts, this library uses a custom builder
          include:
          exclude:
            - '**'