name: Analyze and test code

on:
  pull_request:
    # Some filters on when this actions should run on pull requests
    # https://frontside.com/blog/2020-05-26-github-actions-pull_request/#:~:text=When%20a%20Github%20Actions%20workflow,opened%20%2C%20synchronize%20%2C%20and%20reopened%20.&text=Basic%20pull_request%20usage.
    types: [ synchronize ]
    paths: [ '**.dart' ]

jobs:
  test:
    # The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: ubuntu-latest
    # Sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'

      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.x'

      # Resolve dependencies
      - name: Resolve dependencies
        run: flutter pub get

      # Analysis code
      - name: Check the format of the code
        run: find ./lib/** -name "*.dart" ! -name "*.g.dart" | tr '\n' ' ' | xargs flutter format -l 100 --set-exit-if-changed
      - name: Analyze the code
        run: flutter analyze --no-pub --no-fatal-infos

      # run  flutter widgets tests  and unit tests
      - name: run  flutter widgets tests and unit tests
        run: flutter test --no-pub